((nil . ((projectile-project-compilation-cmd . "cmake -S . -B build;cmake --build build")
	 (compile-command . "cmake -S . -B build;cmake --build build")
         (projectile-project-run-cmd . "./build/GAME")
	 )
      )
 )
